controller_list:
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
  - name: fake_ee_group_controller
    type: $(arg fake_execution_type)
    joints:
      - garra1_joint
initial:  # Define initial robot poses per group
  - group: arm_group
    pose: home
  - group: ee_group
    pose: open