yaren:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_1
  joint2_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_2
  joint3_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_3
  joint4_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_4
  joint5_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_5
  joint6_position_controller:
    type: position_controllers/JointPositionController
    joint: joint_6