arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - joint_1
     - joint_2
     - joint_3
     - joint_4
     - joint_5
     - joint_6
ee_group_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - garra1_joint
  gains:
    joint_1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1